### PR TITLE
Fixed route/query parameters binding when using Nullable data-types.

### LINKED ISSUE #37: As<T> throws InvalidCastException on Nullable types
When using `As<T>` and `AsMultiple<T>` extension methods on `IQueryCollection` or `RouteData` with Nullable data-types as `T` (e.g. `int?`), an `InvalidCastException` is thrown.

This is due the framework unable to cast `int` to `int?` (same for other `Nullable<T>`) directly when using `Convert.ChangeType`.

### PR DESCRIPTION
**Pull request by fdipuma**
Fixes #37 

Added internal helper methods for converting types.

Added unit-tests for nullable binding on query string.

### CODE REVIEW

File: src/Request/ConvertExtensions.cs [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+            {
+                if (value == null) return default(T);
+
+                type = underlyingType;
+            }
+
+            return (T)Convert.ChangeType(value, type);
+        }
+
+        public static IEnumerable<T> ConvertMultipleTo<T>(this IEnumerable<object> values)
```
Comment (jchannon) [inline src/Request/ConvertExtensions.cs]: I think this can be `IEnumerable<string>` for now

**Comment by jchannon** [comment]
Great stuff, thanks! 👍
