### PR TITLE
Fixed published assembly issue

### LINKED ISSUE #82: Sample release version doesn't work
there is no problem with Debug mode.
but in release and publish mode, routing doesn't seems work.

### PR DESCRIPTION
**Pull request by jchannon**
Fixes #82

### CODE REVIEW

File: src/BotwinExtensions.cs [hunk 1]
```diff
@@ -148,9 +147,11 @@ private static void ApplyGlobalBeforeHook(IApplicationBuilder builder, BotwinOpt
         /// </summary>
         /// <param name="services">The <see cref="IServiceCollection"/> to add Botwin to.</param>
         /// <param name="assemblies">Optional array of <see cref="Assembly"/> to add to the services collection. If assemblies are not provided, Assembly.GetEntryAssembly is called.</param>
-        public static void AddBotwin(this IServiceCollection services, params Assembly[] assemblies)
+        public static void AddBotwin(this IServiceCollection services)
```
Comment (JoeStead) [inline src/BotwinExtensions.cs]: We should probably provide an overload so you can specify the assembly your modules belong in explicitly.

Comment (JoeStead) [reply src/BotwinExtensions.cs]: Actually, I don't think you do need this
